### ISSUE TITLE
Hi, 可以请教一下代码块部分是怎么弄的吗？

### ISSUE THREAD

**Issue by 543877815** [ntnyq/ntnyq.github.io#2]
![CW8XD%A9Q8L XJ% HT4Q BF](https://user-images.githubusercontent.com/25082467/56096796-5703c300-5f1f-11e9-8892-69ded235e7d3.png)

**Comment by 543877815** [comment]
感觉样式很精美

**Comment by ntnyq** [comment]
从别人的博文里看到的效果。

[codeblock.js](https://github.com/ntnyq/ntnyq.github.io/blob/dev/themes/next/scripts/codeblock.js)
[custom.styl](https://github.com/ntnyq/ntnyq.github.io/blob/dev/themes/next/source/css/_custom/custom.styl)

在hexo的 [after-post-render](https://hexo.io/zh-cn/api/filter#after-post-render) 过滤器里替换了原来的代码块儿HTML片段，加上了对应的样式，参考上面2个文件。

**Comment by 543877815** [comment]
文章里面可以了！谢谢！
但是这个实现有一点不足就是首页上渲染的部分文章的代码块没有这个效果
我再研究研究...

**Comment by ntnyq** [comment]
一般文章都会设置截断吧 只显示文章概述来保证页面的简洁 不过你可以试试别的 [Hexo过滤器](https://hexo.io/zh-cn/api/filter)。
